version: '3'
services:
  ha:
    container_name: ha
    image: "ghcr.io/home-assistant/home-assistant:2022.7.5"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
