
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  server_port: 443
  ssl_certificate: ./config/ssl/certificate.pem
  ssl_key: ./config/ssl/key.pem